ASP.Server/Models/ErrorViewModel.cs
using System;

namespace ASP.Server.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.Server/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ASP.Server.Database;
using ASP.Server.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis;
using System.Diagnostics;
using static System.Net.Mime.MediaTypeNames;

namespace ASP.Server.Controllers
{
    public class CreateBookModel
    {
        [Required]
        [Display(Name = "Nom")]
        public String Name { get; set; }

        public float Price { get; set; }

        public string Author { get; set; }

        public string Content { get; set; }

        // Ajouter ici tous les champ que l'utilisateur devra remplir pour ajouter un livre

        // Liste des genres séléctionné par l'utilisateur
        public List<int> Genres { get; set; }

        // Liste des genres a afficher à l'utilisateur
        public IEnumerable<Genre> AllGenres { get; init;  }
    }

    public class BookController : Controller
    {
        private readonly LibraryDbContext libraryDbContext;

        public BookController(LibraryDbContext libraryDbContext)
        {
            this.libraryDbContext = libraryDbContext;
        }

        public ActionResult<IEnumerable<Book>> List()
        {
            // récupérer les livres dans la base de donées pour qu'elle puisse être affiché
            List<Book> ListBooks = libraryDbContext.Books.ToList();
            return View(ListBooks);
        }

        public ActionResult<CreateBookModel> Create(CreateBookModel book)
        {
            // Le IsValid est True uniquement si tous les champs de CreateBookModel marqués Required sont remplis
            if (ModelState.IsValid)
            {
                // Il faut intéroger la base pour récupérer l'ensemble des objets genre qui correspond aux id dans CreateBookModel.Genres
                List<Genre> genres = new List<Genre> ();
                foreach(int index in book.Genres) 
                {
                    genres.Add(libraryDbContext.Genre.Where(x => x.Id == index).First());
                }

                // Completer la création du livre avec toute les information nécéssaire que vous aurez ajoutez, et metter la liste des gener récupéré de la base aussi
                libraryDbContext.Add(new Book(book.Name, book.Author, book.Price, book.Content, genres) { });
                libraryDbContext.SaveChanges();
            }

            // Il faut interoger la base pour récupérer tous les genres, pour que l'utilisateur puisse les slécétionné
            return View(new CreateBookModel() { AllGenres = libraryDbContext.Genre.ToList() } );
        }

        public ActionResult<List<Book>> DeleteBook(int id)
        {
            Book book = libraryDbContext.Books.Include(x => x.Genre).Where(x => x.Id == id).First();
            libraryDbContext.Remove(book);
            libraryDbContext.SaveChanges();

            List<Book> ListBooks = libraryDbContext.Books.ToList();

            return RedirectToAction("List");
        }
    }
}

ASP.Server/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ASP.Server.Database;
using ASP.Server.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ASP.Server.Controllers
{
    public class CreateGenreModel
    {
        [Required]
        [Display(Name = "Nom")]
        public String Name { get; set; }

        public List<Book> Books { get; set; }
        public IEnumerable<Book> AllBooks { get; init; }

    }

    public class GenreController : Controller
    {

        private string Name { get; set; }

        private List<Book> BookName { get; set; }

        private readonly LibraryDbContext libraryDbContext;

        public GenreController(LibraryDbContext libraryDbContext)
        {
            this.libraryDbContext = libraryDbContext;
        }

        // A vous de faire comme BookController.List mais pour les genres !
        public ActionResult<CreateGenreModel> Create(CreateGenreModel genre)
        {
            // Le IsValid est True uniquement si tous les champs de CreateBookModel marqués Required sont remplis
            if (ModelState.IsValid)
            {
                // Il faut intéroger la base pour récupérer l'ensemble des objets genre qui correspond aux id dans CreateBookModel.Genres
                List<Book> books = new List<Book>();
                foreach (Book index in genre.Books)
                {
                    books.Add(libraryDbContext.Books.Where(x => x.Id == index.Id).First());
                }

                // Completer la création du livre avec toute les information nécéssaire que vous aurez ajoutez, et metter la liste des gener récupéré de la base aussi
                libraryDbContext.Add(new Genre(genre.Name, books)  { });
                libraryDbContext.SaveChanges();
            }

            // Il faut interoger la base pour récupérer tous les genres, pour que l'utilisateur puisse les slécétionné
            return View(new CreateGenreModel() { AllBooks = libraryDbContext.Books.ToList() });
        }

        public ActionResult<IEnumerable<Genre>> List()
        {
            // récupérer les livres dans la base de donées pour qu'elle puisse être affiché
            List<Genre> ListGenre = libraryDbContext.Genre.ToList();
            return View(ListGenre);
        }

    }
}

ASP.Server/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASP.Server.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.Server.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.Server/Views/Book/Create.cshtml
@using ASP.Server.Controllers
@model CreateBookModel
@{
    ViewData["Title"] = "Add a book";
}
<style>
.input-group {
    margin-top:10px;
    display:flex;
    justify-content:space-between;
    flex-wrap:wrap;
}
input, textarea, select {
    flex-basis:85%;
}
label {
    flex-basis:10%;
}
</style>

<!-- Voici une facon de faire, mais ce n'est pas la seul, a vous de jouer ! -->
<form asp-controller="Book" asp-action="Create">
    <div class="input-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
    </div>
        <div class="input-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" />
    </div>
        <div class="input-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" />
    </div>
    <div class="input-group">
        <label asp-for="Content"></label>
        <input asp-for="Content" />
    </div>
    <div class="input-group">
        <label asp-for="Genres"></label>
        <!--Si la page rend une erreur a cette ligne, c'est que vous n'avez pas envoyé la liste des genres dans le Controller !!! ! -->
        <select asp-for="Genres" asp-items="@(new SelectList(Model.AllGenres,"Id","Name"))">
        </select>
    </div>
    <input type="submit" value="Add" style="width: 100%; margin-top: 50px" />
</form>

ASP.Server/Views/Book/List.cshtml
@using ASP.Server.Model
@model IEnumerable<Book>
@{
    ViewData["Title"] = "Home Page";
}

<style>
    table,
    td {
        border: 1px solid #333;
    }

    thead,
    tfoot {
        background-color: #333;
        color: #fff;
    }


</style>

<div class="listeBooks">
    <h1>Liste des livres:</h1>
    <!-- la liste des genres est dans la variable Model qui est typé en ligne 3, elle correspond à 
    la variable xxx dans View(xxx) du controller -->    

    <fieldset>
        @foreach (var genre in Model)
        {
            <input type="checkbox" name="test" />
            <label> test </label>
        }
    </fieldset>

    <table>
        <thead>
            <tr>
                <th> Name</th>
                <th> Author</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.Author</td>
                    <td>
                        <form asp-controller="Book" asp-action="DeleteBook">
                            <input type="hidden" name="id" value="@book.Id" />
                            <input type="submit" value="Delete" style="width: 100%; margin-top: 50px"/>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table> 
</div>

ASP.Server/Views/Genre/Create.cshtml
@using ASP.Server.Controllers
@model CreateGenreModel
@{
    ViewData["Title"] = "Add a genre";
}
<style>
.input-group {
    margin-top:10px;
    display:flex;
    justify-content:space-between;
    flex-wrap:wrap;
}
input, textarea, select {
    flex-basis:85%;
}
label {
    flex-basis:10%;
}
</style>

<!-- Voici une facon de faire, mais ce n'est pas la seul, a vous de jouer ! -->
<form asp-controller="Genre" asp-action="Create">
    <div class="input-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
    </div>

    <div class="input-group">
        <label asp-for="Books"></label>
        <!--Si la page rend une erreur a cette ligne, c'est que vous n'avez pas envoyé la liste des genres dans le Controller !!! ! -->
        <select asp-for="Books" asp-items="@(new SelectList(Model.AllBooks,"Id", "Title"))">
        </select>
    </div>
    <input type="submit" value="Add" style="width: 100%; margin-top: 50px" />
</form>

ASP.Server/Views/Genre/List.cshtml
@using ASP.Server.Model

@model IEnumerable<Genre>
@{
    ViewData["Title"] = "Liste Genre";
}

<div class="listeGenres">
    <h1>Liste des Genres:</h1>
    <!-- la liste des genres est dans la variable Model qui est typé en ligne 3, elle correspond à la variable xxx dans View(xxx) du controller -->
    @foreach (var genre in Model)
    {
        <h1>@genre.Name</h1>
    }
</div>

ASP.Server/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP.Server/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utfcolorname="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">bibliothéque</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="List">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="List">Genres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Create">Add new book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Create">Add new genre</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav float-right">
                        <li class="nav-item float-right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="swagger" asp-action="">Swagger</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - APP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>